apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  namespace: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: ssj4358/webfront:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_DATABASE_HOST
          value: "mysql-service.flask-app.svc.cluster.local"
        - name: MYSQL_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE_USER  # Secret의 실제 키 이름 사용
        - name: MYSQL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE_PASSWORD  # Secret의 실제 키 이름 사용