apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flask-app

resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml

images:
  - name: ssj4358/webfront
    newTag: latest
    